config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:show, :index]
    resources :organizations, except: [:new, :edit]
    resources :workspaces, except: [:new, :edit]
    resources :projects, only: [:create, :update, :destroy, :index, :show]
    resources :tasks, only: [:create, :show, :update, :destroy]
    resources :workspace_project_memberships, only: [:create]
    resources :team_memberships, only: [:create]
    resources :search, only: [:index]
    resources :membership_requests, only: [:create, :index]
    resources :organization_memberships, only: [:create]
    resources :organization_membership_notifications, only: [:create, :index]
    resources :project_membership_notifications, only: [:create, :index]
    resources :assignments, only: [:create]
  end
end

app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br").html_safe if flash[:errors] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Manifold</title>
  <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
  <script src="http://widget.cloudinary.com/global/all.js" type="text/javascript" charset="utf-8"></script>

  <script type="text/javascript" charset="utf-8">
    window.CLOUDINARY_OPTIONS = {
      cloud_name: "<%=ENV['CLOUD_NAME']%>",
      upload_preset: "<%= ENV['UPLOAD_PRESET'] %>"
    };
  </script>
  <%= stylesheet_link_tag    "application", media: "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>

</head>
<body>
  <!-- <h1 class="app-name">Manifold</h1> -->
<%= render "layouts/errors" %>
 <!-- <% if logged_in? %> -->

<!-- <% end %> -->

<%= yield %>
<!-- <%= button_to "Sign Out", session_url, method: :delete %> -->

</body>
</html>